### ISSUE TITLE
API returns empty results

### ISSUE THREAD

**Issue by g0kuvonlange** [ashleykleynhans/runpod-worker-oobabooga#2]
So I first did a /list request which returned me my models, I chose my ([custom model](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ)) that I modified in the standalone dockerfile before building. Then I copied the model name from the /list request and did /load and passed it into the args, which returned me all the settings just like the doc api examples. But when I try the /chat or /generate endpoints my returns are always empty:

**/generate**

`{'delayTime': 6158, 'executionTime': 177, 'id': 'sync-3da22c16-2d1e-4df7-8b3e-be1e2515fb22', 'output': {'results': [{'text': ''}]}, 'status': 'COMPLETED'}`

**/chat**

`{'delayTime': 7277, 'executionTime': 185, 'id': 'sync-82cbf2ec-08f7-4844-a130-0dd514e29b80', 'output': {'results': [{'history': {'internal': [], 'visible': []}}]}, 'status': 'COMPLETED'}`

Have tried to look at the logs to find out whats the problem, but system and container are kinda shallow. What should I do?

**Comment by ashleykleynhans** [comment]
This usually means that the model isn't loaded correctly.  You should be able to start a web terminal and check what the issue is by viewing the log: `/workspace/logs/textgen.log`.
