### ISSUE TITLE
how to trust-remote-code?

### ISSUE THREAD

**Issue by jasonz1360** [ashleykleynhans/runpod-worker-oobabooga#4]
as title, how can i config trust-remote-code in runpod environment variables.

**Comment by ashleykleynhans** [comment]
I don't know what you are referring to by "trust-remote-code".

**Comment by jasonz1360** [comment]
`ValueError: Loading models/THUDM_glm-10b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.`

Hi ashleykleynhans,  because an error reported as above, so i wanted to know how to set trust_remote_code in docker environment variables. 

What should I do?

**Comment by ashleykleynhans** [comment]
@jasonz1360 You can add an environment variable called `UI_ARGS` with a value of `--trust_remote_code`.

**Comment by ashleykleynhans** [comment]
@jasonz1360 you can edit the appropriate start.sh script and add `--trust-remote-code`.
