### ISSUE TITLE
an pytorch input issue when using the TheBloke/Synthia-70B-v1.2b-GPTQ model

### ISSUE THREAD

**Issue by nchamroukhi** [ashleykleynhans/runpod-worker-oobabooga#5]
shape '[1, 41, 64, 128]' is invalid for input of size 41984

2023-10-24 13:34:02.637[][error]ERROR | Error while running job 8ff4c77d-0d94-4c63-bb12-8d8e971e4242-e1: shape '[1, 41, 64, 128]' is invalid for input of size 41984
{5 items
"dt":"2023-10-24 11:34:02.637429"
"endpointid":""
"level":"error"
"message":"ERROR | Error while running job 8ff4c77d-0d94-4c63-bb12-8d8e971e4242-e1: shape '[1, 41, 64, 128]' is invalid for input of size 41984"
"workerId":""
}

**Comment by nchamroukhi** [comment]
2023-10-24 13:34:02.637[rzb4d892djvugp][error]ERROR | Error while running job 8ff4c77d-0d94-4c63-bb12-8d8e971e4242-e1: shape '[1, 41, 64, 128]' is invalid for input of size 41984
{5 items
"dt":"2023-10-24 11:34:02.637429"
"endpointid":"8hecde435ws1dn"
"level":"error"
"message":"ERROR | Error while running job 8ff4c77d-0d94-4c63-bb12-8d8e971e4242-e1: shape '[1, 41, 64, 128]' is invalid for input of size 41984"
"workerId":"rzb4d892djvugp"
}

**Comment by ashleykleynhans** [comment]
@nchamroukhi which GPU type were you using for this?

**Comment by ashleykleynhans** [comment]
@nchamroukhi I have updated the worker, please reinstall and try again.

**Comment by ashleykleynhans** [comment]
Also please note you need at least a 48GB GPU for the 70B model, it will not fit into a 24GB GPU.

**Comment by nchamroukhi** [comment]
Ok, thank you will try it
