### ISSUE TITLE
Service not ready yet. Retrying...

### ISSUE THREAD

**Issue by aeidme** [ashleykleynhans/runpod-worker-oobabooga#7]
Hello,

First of all, thank you a lot for this contribution. I have followed all your steps with the network volume and everything is going well except when the actual oobabooga service is about to start it gives me this error:

`INFO | Service not ready yet. Retrying...`

Do you have any idea why this is happening? Thanks a lot!

**Comment by ashleykleynhans** [comment]
This is not an error, its normal, its waiting for the Ooobabooga API to come up (thats why it says INFO and not ERROR).

**Comment by aeidme** [comment]
Thank you for your quick reply @ashleykleynhans!
Yes I thought so but it kept retrying for more than 15 minutes, is that normal? So I turned it off.

**Comment by ashleykleynhans** [comment]
No, its not normal to take 15 minutes, should take about 1 minute at the most.
You can start a Web Terminal on the worker and check the log to see whats happening.
```bash
cat /workspace/logs/textgen.log
```

**Comment by aeidme** [comment]
Thanks a lot for the hint.

This is the error:
```
Traceback (most recent call last):
  File "/runpod-volume/text-generation-webui/server.py", line 222, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/runpod-volume/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/runpod-volume/text-generation-webui/modules/models.py", line 343, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "/runpod-volume/text-generation-webui/modules/exllama.py", line 75, in from_pretrained
    model = ExLlama(config)
  File "/workspace/venv/lib/python3.10/site-packages/exllama/model.py", line 743, in __init__
    with safe_open(path, framework = "pt", device = "cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```
I'm using Vicuna model from here: https://huggingface.co/lmsys/vicuna-13b-v1.5-16k

**Comment by ashleykleynhans** [comment]
This is not an exllama compatible model, so you can't use the exllama model loader to load it.

You should edit the `start_network_volume.sh` script and remove line 26:
```
--loader exllama \
```

Then build a new image, with a new tag version and then it should use Transformers to load the model instead of exllama and then it should be fine.

**Comment by aeidme** [comment]
@ashleykleynhans thank you very much. It's now working.

One last question please, do you know how to send a post request that contains the following parameters: max tokens to return, seed, sampling parameters etc?

**Comment by ashleykleynhans** [comment]
@aeidme its the standard oobabooga deprecated API, you use all of the parameters that it uses, you can view the schemas for more information https://github.com/ashleykleynhans/runpod-worker-oobabooga/tree/main/schemas

**Comment by aeidme** [comment]
@ashleykleynhans thank you once again. When I add `"max_new_tokens": 250` the request fails and gives me this error: `output json is invalid; max size is 20 MB` although 250 is the default.

**Comment by ashleykleynhans** [comment]
Works fine for me, it will do that if you add invalid stuff to your request.

<img width="863" alt="Screenshot 2023-11-13 at 10 51 08" src="https://github.com/ashleykleynhans/runpod-worker-oobabooga/assets/886709/9183f934-8008-4d38-abdb-9af3c5bbe42c">

**Comment by ashleykleynhans** [comment]
Error handling has been improved, so if you pull the latest changes and rebuild the Docker image, you should see a more meaningful error message.
