### ISSUE TITLE
Running on any non GPU server?

### ISSUE THREAD

**Issue by distributev** [ashleykleynhans/runpod-worker-oobabooga#9]
Do I understand correctly that this is supposed to deploy text-generation-webui locally on a machine without GPU (or on normal VPS servers i.e. DigitalOcean) and then it will allow to use  text-generation-webui API linked to a serverless runpod account?

**Comment by ashleykleynhans** [comment]
No, that is incorrect, this needs to be deployed on RunPod.

**Comment by distributev** [comment]
So what is the point/the difference vs just deploying/using text-generation-webui normally on runpod.io (and paying runpod's GPU rates)

deploying on a normal VPS i.e. DigitalOcean means paying the server most of the times at lower non-GPU rates and then, only when an llm API is being called, pay the runpod.io serverless fees based on usage.

**Comment by ashleykleynhans** [comment]
@distributev Go ask RunPod Discord please, this is not in the scope of this repo and in future read the docs instead of wasting my valuable time.

**Comment by distributev** [comment]
Ok, I'll do that. Thank you for your project and for the first answer. I was looking for something like I described and then, when I found your project and looked a bit through the source code, I thought it was intended to achieve that.
